language: php

php:
  - 7.0
  - 7.1
  - 7.2

env:
  - SYMFONY_VERSION="2.8.*"
  - SYMFONY_VERSION="3.3.*"
  - SYMFONY_VERSION="3.4.x-dev"

matrix:
  exclude:
    - php: 7.0
      env: SYMFONY_VERSION="3.4.x-dev" # Symfony >= 3.4 PHP requirement is ^7.1.3
  allow_failures:
    - env: SYMFONY_VERSION="3.4.x-dev" # Symfony unstable version, allowed to fail

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer selfupdate
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/framework-bundle:${SYMFONY_VERSION}" --no-update; composer require "symfony/security-bundle:${SYMFONY_VERSION}" --no-update;  composer require --dev "symfony/yaml:${SYMFONY_VERSION}" --no-update; fi;
  - if [ "$SYMFONY_VERSION" == "3.4.x-dev" ]; then composer require "symfony/cache:${SYMFONY_VERSION}" --no-update; fi;

install: composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script:
  - vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
  email: eugone.yann@gmail.com
