language: php

php:
  - 7.0
  - 7.1
  - 7.2

env:
  - SYMFONY_VERSION="2.8.*"
  - SYMFONY_VERSION="3.3.*"
  - SYMFONY_VERSION="3.4.x-dev"
  - SYMFONY_VERSION="4.0.x-dev"

matrix:
  exclude:
    # Symfony >= 3.4 PHP requirement is ^7.1.3
    - php: 7.0
      env: SYMFONY_VERSION="3.4.x-dev"
    - php: 7.0
      env: SYMFONY_VERSION="4.0.x-dev"
  allow_failures:
    # Symfony unstable versions, allowed to fail
    - env: SYMFONY_VERSION="3.4.x-dev"
    - env: SYMFONY_VERSION="4.0.x-dev"

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer selfupdate
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;

install: composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script:
  - vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
  email: eugone.yann@gmail.com
